name: Android CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-debug:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Prepare Android debug keystore (CI)
        run: |
          mkdir -p "$HOME/.android"
          mkdir -p "$HOME/.config/.android"
          if [ ! -f "$HOME/.android/debug.keystore" ]; then
            keytool -genkey -v -keystore "$HOME/.android/debug.keystore" \
              -storepass android -alias androiddebugkey -keypass android \
              -dname "CN=Android Debug,O=Android,C=US" -keyalg RSA -keysize 2048 -validity 10000
          fi
          cp "$HOME/.android/debug.keystore" "$HOME/.config/.android/debug.keystore" || true

      - name: Install Android SDK components
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          yes | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses || true
          yes | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0"

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug -x lint

      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk

  release:
    name: Release with APK
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build-debug
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Prepare Android debug keystore (CI)
        run: |
          mkdir -p "$HOME/.android"
          mkdir -p "$HOME/.config/.android"
          if [ ! -f "$HOME/.android/debug.keystore" ]; then
            keytool -genkey -v -keystore "$HOME/.android/debug.keystore" \
              -storepass android -alias androiddebugkey -keypass android \
              -dname "CN=Android Debug,O=Android,C=US" -keyalg RSA -keysize 2048 -validity 10000
          fi
          cp "$HOME/.android/debug.keystore" "$HOME/.config/.android/debug.keystore" || true

      - name: Install Android SDK components
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          yes | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses || true
          yes | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0"

      - name: Build Release APK
        run: ./gradlew :app:assembleRelease -x lint

      - name: Upload APKs to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
